@startuml architecture

skinparam componentStyle rectangle

actor "User"

component "Frontend" %lighten("#b6d7a8", 20) {
  port "Browser" as WEB
  port "HTTP" as HTTP_F

  component "View" as FV #b6d7a8

  component "Controller" as FC #a4c2f4

  component "Model" as FM #dd7e6b
}

component "Backend" %lighten("#a4c2f4", 20) {
  port "HTTP" as HTTP_B
  port "TCP" as TCP_B

  component "Presentation layer" #b6d7a8 {
    component "Application controller" as AC
  }
  
  component "Application layer" #a4c2f4 {
    component "Application service" as AS
  }

  component "Persistence layer" #dd7e6b {
    component "Application repository" as AR
  }
}

component "Data layer" %lighten("#dd7e6b", 20) {
  port "TCP" as TCP_D

  database "Database" as DB
}

User -> WEB : 1 Uses
WEB -> FV: 2
FV -> FC : 3

FC -> FM : 4 Manipulates
FM -> HTTP_F : 5 Calls API

HTTP_F -> FM : 16
FM -down-> FC : 17 Passes data

FC -> FV : 18 Updates
FV -> WEB : 19
WEB -> User : 20 Sees


HTTP_F <-> HTTP_B : REST API


HTTP_B -> AC : 6 Handles request
AC -> AS : 7 Calls
AS -> AR : 8 Uses

AR -> TCP_B : 9 Requests
TCP_B <-> TCP_D : Database connection
TCP_D -> DB : 10 Persists
DB -> TCP_D : 11 Returns
TCP_B -> AR : 12

AR -down-> AS : 13 Passes data
AS -up-> AC : 14
AC -> HTTP_B : 15 Replies

@enduml