@startuml structs

entity TodoEntity {
  id: string | number
  description: string
  completed: boolean
  create_date: number
}

struct CreateTodoDto {
  description: string
  completed?: boolean = false
}

struct SelectTodoByIdDto {
  id: string | number
}

struct GetTodosByQueryDto {
  completed?: boolean
  search?: string
  from_date?: number
  to_date?: number
}

struct UpdateTodoDto {
  description?: string
  completed?: boolean
}

@enduml